[2024-10-03T19:00:01.030+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: clever_main_DAG.upload_to_postgres_fmcsa_complaints manual__2024-10-03T18:55:24.253049+00:00 [queued]>
[2024-10-03T19:00:01.036+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: clever_main_DAG.upload_to_postgres_fmcsa_complaints manual__2024-10-03T18:55:24.253049+00:00 [queued]>
[2024-10-03T19:00:01.037+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 1
[2024-10-03T19:00:01.045+0000] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): upload_to_postgres_fmcsa_complaints> on 2024-10-03 18:55:24.253049+00:00
[2024-10-03T19:00:01.048+0000] {standard_task_runner.py:57} INFO - Started process 561 to run task
[2024-10-03T19:00:01.051+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'clever_main_DAG', 'upload_to_postgres_fmcsa_complaints', 'manual__2024-10-03T18:55:24.253049+00:00', '--job-id', '16', '--raw', '--subdir', 'DAGS_FOLDER/clever_main_DAG.py', '--cfg-path', '/tmp/tmpwl98nmrv']
[2024-10-03T19:00:01.053+0000] {standard_task_runner.py:85} INFO - Job 16: Subtask upload_to_postgres_fmcsa_complaints
[2024-10-03T19:00:01.085+0000] {task_command.py:410} INFO - Running <TaskInstance: clever_main_DAG.upload_to_postgres_fmcsa_complaints manual__2024-10-03T18:55:24.253049+00:00 [running]> on host 0ed64f12ba94
[2024-10-03T19:00:01.148+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='alec.ventura' AIRFLOW_CTX_DAG_ID='clever_main_DAG' AIRFLOW_CTX_TASK_ID='upload_to_postgres_fmcsa_complaints' AIRFLOW_CTX_EXECUTION_DATE='2024-10-03T18:55:24.253049+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-10-03T18:55:24.253049+00:00'
[2024-10-03T19:00:01.240+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/scripts/clever_main_pipeline.py", line 13, in upload_to_postgres
    upload_overwrite_table(raw_df, table_name)
  File "/opt/airflow/dags/scripts/postgres_helper.py", line 18, in upload_overwrite_table
    df.to_sql(f'{table_name}', engine, index=False, if_exists='overwrite')
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/generic.py", line 2882, in to_sql
    method=method,
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/sql.py", line 706, in to_sql
    raise ValueError(f"'{if_exists}' is not valid for if_exists")
ValueError: 'overwrite' is not valid for if_exists
[2024-10-03T19:00:01.249+0000] {taskinstance.py:1350} INFO - Marking task as FAILED. dag_id=clever_main_DAG, task_id=upload_to_postgres_fmcsa_complaints, execution_date=20241003T185524, start_date=20241003T190001, end_date=20241003T190001
[2024-10-03T19:00:01.257+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 16 for task upload_to_postgres_fmcsa_complaints ('overwrite' is not valid for if_exists; 561)
[2024-10-03T19:00:01.281+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2024-10-03T19:00:01.296+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
